name: coap
description: A CoAP library for Dart. A full implementation of am IPV4/6 CoAP client
version: 2.0.1
homepage: https://github.com/shamblett/coap

environment:
  sdk: ">=2.6.0  <3.0.0"

dependencies:
 typed_data: '^1.1.6'
 collection: '^1.14.11'
 hex: '^0.1.2'
 executor: '^2.1.0'
 logging: '^0.11.3+2'
 event_bus: '^1.0.1'
 pedantic: '^1.5.0'
 string_scanner: '^1.0.5'
 date_format: '^1.0.6'
 build: '^1.2.2'
 yaml: '^2.2.0'
 path: '^1.6.4'

dev_dependencies:
  test: '^1.3.0'
  build_runner: '^1.8.1'
  pana: '^0.13.4'


