name: coap
description: A CoAP library for Dart. A full implementation of am IPV4/6 CoAP client
version: 2.0.2
homepage: https://github.com/shamblett/coap

environment:
  sdk: '>=2.12.0-29.10.beta <3.0.0'

dependencies:
 typed_data: '^1.3.0-nullsafety.5'
 collection: '^1.15.0-nullsafety.5'
 hex: '^0.1.2'
 executor: '^2.2.1'
 logging: '^0.11.4'
 event_bus: '^1.1.1'
 pedantic: '^1.10.0-nullsafety.3'
 string_scanner: '^1.1.0-nullsafety.3'
 date_format: '^1.0.9'
 build: '^1.6.1'
 yaml: '^2.2.1'
 path: '^1.8.0-nullsafety.3'

dev_dependencies:
  test: '^1.16.0-nullsafety.16'
  build_runner: '^1.11.0'
  pana: '^0.14.10'


