name: coap
description: A CoAP library for Dart. A full implementation of am IPV4/6 CoAP client
version: 3.1.0
homepage: https://github.com/shamblett/coap

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
 hex: ^0.2.0
 executor: ^2.2.2
 logging: ^1.0.1
 event_bus: ^2.0.0
 string_scanner: ^1.1.0
 date_format: ^2.0.4
 build: ^2.1.0
 yaml: ^3.1.0

dev_dependencies:
  test: '^1.17.12'
  build_runner: '^2.1.2'
  pedantic: '^1.11.1'


